import type { PlatformSubs } from "@/lib/types"

// Generate mock data for the four platforms
export const mockData: PlatformSubs[] = [
  // vercel.app sites
  {
    _id: "1",
    url: "portfolio.vercel.app",
    clicks: 5600000,
    trafficShare: "6.39%",
    change: "-18.03%",
    topKeyword: "portfolio template",
    platform: "vercel.app",
  },
  {
    _id: "2",
    url: "dashboard.vercel.app",
    clicks: 4900000,
    trafficShare: "5.63%",
    change: "0.60%",
    topKeyword: "admin dashboard",
    platform: "vercel.app",
  },
  {
    _id: "3",
    url: "nextjs-blog.vercel.app",
    clicks: 4500000,
    trafficShare: "5.09%",
    change: "-8.30%",
    topKeyword: "next.js blog",
    platform: "vercel.app",
  },
  {
    _id: "4",
    url: "ecommerce-store.vercel.app",
    clicks: 3700000,
    trafficShare: "4.16%",
    change: "-19.32%",
    topKeyword: "online shop template",
    platform: "vercel.app",
  },
  {
    _id: "5",
    url: "landing-page.vercel.app",
    clicks: 2600000,
    trafficShare: "2.96%",
    change: "-10.94%",
    topKeyword: "landing page template",
    platform: "vercel.app",
  },
  {
    _id: "6",
    url: "game-app.vercel.app",
    clicks: 2200000,
    trafficShare: "2.54%",
    change: "-15.17%",
    topKeyword: "javascript games",
    platform: "vercel.app",
  },
  {
    _id: "7",
    url: "weather-app.vercel.app",
    clicks: 1800000,
    trafficShare: "2.03%",
    change: "-14.68%",
    topKeyword: "weather forecast",
    platform: "vercel.app",
  },
  {
    _id: "8",
    url: "react-demo.vercel.app",
    clicks: 7800000,
    trafficShare: "8.75%",
    change: "2.35%",
    topKeyword: "react examples",
    platform: "vercel.app",
  },
  {
    _id: "9",
    url: "ai-tools.vercel.app",
    clicks: 3100000,
    trafficShare: "3.42%",
    change: "-5.67%",
    topKeyword: "ai tools online",
    platform: "vercel.app",
  },
  {
    _id: "10",
    url: "crypto-tracker.vercel.app",
    clicks: 2500000,
    trafficShare: "2.89%",
    change: "1.23%",
    topKeyword: "bitcoin price",
    platform: "vercel.app",
  },
  {
    _id: "11",
    url: "saas-template.vercel.app",
    clicks: 2300000,
    trafficShare: "2.65%",
    change: "8.45%",
    topKeyword: "saas boilerplate",
    platform: "vercel.app",
  },
  {
    _id: "12",
    url: "music-player.vercel.app",
    clicks: 2100000,
    trafficShare: "2.34%",
    change: "-3.21%",
    topKeyword: "web music player",
    platform: "vercel.app",
  },
  {
    _id: "13",
    url: "photo-gallery.vercel.app",
    clicks: 1900000,
    trafficShare: "2.12%",
    change: "-7.89%",
    topKeyword: "image gallery",
    platform: "vercel.app",
  },
  {
    _id: "14",
    url: "chat-app.vercel.app",
    clicks: 1750000,
    trafficShare: "1.98%",
    change: "-2.34%",
    topKeyword: "chat application",
    platform: "vercel.app",
  },
  {
    _id: "15",
    url: "todo-app.vercel.app",
    clicks: 1650000,
    trafficShare: "1.87%",
    change: "0.78%",
    topKeyword: "todo list app",
    platform: "vercel.app",
  },
  {
    _id: "16",
    url: "new-project.vercel.app",
    clicks: 3200000,
    trafficShare: "1.87%",
    change: "New",
    topKeyword: "project template",
    platform: "vercel.app",
  },
  {
    _id: "17",
    url: "new-portfolio.vercel.app",
    clicks: 2800000,
    trafficShare: "1.65%",
    change: "New",
    topKeyword: "portfolio examples",
    platform: "vercel.app",
  },
  {
    _id: "18",
    url: "ai-assistant.vercel.app",
    clicks: 5400000,
    trafficShare: "3.21%",
    change: "12.5%",
    topKeyword: "ai chatbot",
    platform: "vercel.app",
  },
  {
    _id: "19",
    url: "learning-platform.vercel.app",
    clicks: 4900000,
    trafficShare: "2.98%",
    change: "15.7%",
    topKeyword: "online courses",
    platform: "vercel.app",
  },
  {
    _id: "20",
    url: "digital-agency.vercel.app",
    clicks: 4500000,
    trafficShare: "2.76%",
    change: "11.2%",
    topKeyword: "digital marketing",
    platform: "vercel.app",
  },

  // github.io sites
  {
    _id: "21",
    url: "username.github.io",
    clicks: 8600000,
    trafficShare: "3.45%",
    change: "9%",
    topKeyword: "github pages",
    platform: "github.io",
  },
  {
    _id: "22",
    url: "project-docs.github.io",
    clicks: 8600000,
    trafficShare: "2.87%",
    change: "17%",
    topKeyword: "documentation template",
    platform: "github.io",
  },
  {
    _id: "23",
    url: "open-source.github.io",
    clicks: 9000000,
    trafficShare: "3.12%",
    change: "-2%",
    topKeyword: "open source projects",
    platform: "github.io",
  },
  {
    _id: "24",
    url: "code-examples.github.io",
    clicks: 8600000,
    trafficShare: "2.76%",
    change: "-5%",
    topKeyword: "programming examples",
    platform: "github.io",
  },
  {
    _id: "25",
    url: "developer-blog.github.io",
    clicks: 8500000,
    trafficShare: "2.65%",
    change: "-5%",
    topKeyword: "coding blog",
    platform: "github.io",
  },
  {
    _id: "26",
    url: "tech-notes.github.io",
    clicks: 8400000,
    trafficShare: "2.54%",
    change: "-7%",
    topKeyword: "programming notes",
    platform: "github.io",
  },
  {
    _id: "27",
    url: "new-library.github.io",
    clicks: 2800000,
    trafficShare: "1.65%",
    change: "New",
    topKeyword: "javascript library",
    platform: "github.io",
  },
  {
    _id: "28",
    url: "framework-docs.github.io",
    clicks: 4900000,
    trafficShare: "2.98%",
    change: "15.7%",
    topKeyword: "web framework",
    platform: "github.io",
  },

  // netlify.app sites
  {
    _id: "29",
    url: "jamstack-site.netlify.app",
    clicks: 7600000,
    trafficShare: "2.10%",
    change: "0.9%",
    topKeyword: "jamstack examples",
    platform: "netlify.app",
  },
  {
    _id: "30",
    url: "static-blog.netlify.app",
    clicks: 7400000,
    trafficShare: "1.99%",
    change: "-1.2%",
    topKeyword: "static site generator",
    platform: "netlify.app",
  },
  {
    _id: "31",
    url: "gatsby-demo.netlify.app",
    clicks: 7200000,
    trafficShare: "1.88%",
    change: "-2.5%",
    topKeyword: "gatsby js",
    platform: "netlify.app",
  },
  {
    _id: "32",
    url: "hugo-site.netlify.app",
    clicks: 7000000,
    trafficShare: "1.77%",
    change: "-3.8%",
    topKeyword: "hugo framework",
    platform: "netlify.app",
  },
  {
    _id: "33",
    url: "eleventy-blog.netlify.app",
    clicks: 6800000,
    trafficShare: "1.66%",
    change: "-4.2%",
    topKeyword: "11ty",
    platform: "netlify.app",
  },
  {
    _id: "34",
    url: "new-store.netlify.app",
    clicks: 2400000,
    trafficShare: "1.43%",
    change: "New",
    topKeyword: "ecommerce template",
    platform: "netlify.app",
  },
  {
    _id: "35",
    url: "headless-cms.netlify.app",
    clicks: 4100000,
    trafficShare: "2.54%",
    change: "11.8%",
    topKeyword: "headless cms",
    platform: "netlify.app",
  },

  // js.org sites
  {
    _id: "36",
    url: "library.js.org",
    clicks: 6600000,
    trafficShare: "1.55%",
    change: "-5.6%",
    topKeyword: "javascript libraries",
    platform: "js.org",
  },
  {
    _id: "37",
    url: "framework.js.org",
    clicks: 6400000,
    trafficShare: "1.44%",
    change: "-6.9%",
    topKeyword: "js frameworks",
    platform: "js.org",
  },
  {
    _id: "38",
    url: "tools.js.org",
    clicks: 6200000,
    trafficShare: "1.33%",
    change: "-7.3%",
    topKeyword: "javascript tools",
    platform: "js.org",
  },
  {
    _id: "39",
    url: "resources.js.org",
    clicks: 6000000,
    trafficShare: "1.22%",
    change: "-8.7%",
    topKeyword: "javascript resources",
    platform: "js.org",
  },
  {
    _id: "40",
    url: "new-toolkit.js.org",
    clicks: 2000000,
    trafficShare: "1.21%",
    change: "New",
    topKeyword: "javascript toolkit",
    platform: "js.org",
  },
  {
    _id: "41",
    url: "components.js.org",
    clicks: 3800000,
    trafficShare: "2.32%",
    change: "10.5%",
    topKeyword: "web components",
    platform: "js.org",
  },
]

